### PR TITLE
Relational Database ADR

### PR DESCRIPTION
**Pull request by eeeady**
# [ADR to evaluate migrating MariaDB from EC2 to RDS](https://github.com/OHS-Hosting-Infrastructure/infrastructure/issues/25)

Changes proposed in this pull request:

- Adds ADR with decision of how to restructure the databases/management

### CODE REVIEW

**Comment by ssatagopan** [comment]
@eeeady do we need to consider scenarios where different apps may need access to the same data? not sure how much user profile data is kept in LDAP vs. app databases, but that's one potential use case. Don't think it changes the decision, but might want to include some content in ADR about that.

**Comment by eeeady** [comment]
As a general rule of thumb, apps should not share databases. If they need to share data between them, the devs should create APIs to share said data.

**Review by ssatagopan — APPROVED** [review]
LGTM

**Review by nateprice18f — COMMENTED** [review]
I've reviewed the proposed DB changes and agree with the move from EC2 shared VM resources to isolated RDS resources.

**Review by kilbergr — APPROVED** [review]
I agree with this rationale. Thank you for the options.

**Comment by eeeady** [comment]
Thanks for the reviews all!

**Pull request merged**
