### PR TITLE
Remove obsolete onboarding instructions

### PR DESCRIPTION
**Pull request by rpdelaney**
# Not Jira

Changes proposed in this pull request:

- Remove onboarding instruction about AWS read only access.
- Remove onboarding instruction about email lists

### CODE REVIEW

**Review by ssatagopan — CHANGES_REQUESTED** [review]
Instead of removing the whole section, it would be more accurate to say "Add the new member to the team google groups (headstart-hosting@truss.works and headstart-alerts@truss.works)

**Comment by rpdelaney** [comment]
> Instead of removing the whole section, it would be more accurate to say "Add the new member to the team google groups ([headstart-hosting@truss.works](mailto:headstart-hosting@truss.works) and [headstart-alerts@truss.works](mailto:headstart-alerts@truss.works))

Can do. We have this in the ["Getting started" google doc](https://docs.google.com/document/d/1eSzmHqwlhjcDgAZOrvIIEq-FXzP7cC1dZcOkmEc5zhE/edit#). Should it come out and be moved here? 

> Ask Sanjay to add you to the team emails

**Comment by ssatagopan** [comment]
> > Instead of removing the whole section, it would be more accurate to say "Add the new member to the team google groups ([headstart-hosting@truss.works](mailto:headstart-hosting@truss.works) and [headstart-alerts@truss.works](mailto:headstart-alerts@truss.works))
> 
> Can do. We have this in the ["Getting started" google doc](https://docs.google.com/document/d/1eSzmHqwlhjcDgAZOrvIIEq-FXzP7cC1dZcOkmEc5zhE/edit#). Should it come out and be moved here?:
> 
> > Ask Sanjay to add you to the team emails

Yeah, no need to have it in both the Google Doc and here, so we can use this as the one doc.

**Comment by rpdelaney** [comment]
69e710e744e9bcff98020ce64736920648bbe7ae

**Review by ssatagopan — APPROVED** [review]
LGTM

**Pull request merged**
