### PR TITLE
VPN access list

### PR DESCRIPTION
**Pull request by jerels**
# [Create a VPN Access Doc](https://github.com/OHS-Hosting-Infrastructure/infrastructure/issues/185)

a list of folks w/ VPN access

### CODE REVIEW

**Review by ssatagopan — COMMENTED** [review]
Might want to include what app and/or team they are part of, i.e. HSICC/ECLKC, 18F, Truss, Paradiso/iPD, EEC/ICF, etc.

**Comment by kilbergr** [comment]
Yeah I agree with Sanjay. It would be great to have a team and notes column (I suspect many of these the team will get us halfway there but not all the way). Kind of like this but without the instance ID, type, and env columns: https://github.com/OHS-Hosting-Infrastructure/infrastructure/blob/main/docs/how-we-work/hosted-apps.md

**Review by kilbergr — CHANGES_REQUESTED** [review]
Wrote the comment on the pr rather than the file.

**Comment by eeeady** [comment]
I'd say this is fine. We should start a new jira ticket to revoke the remaining certs we can't connect to a "real" person.

**Comment by jerels** [comment]
@kilbergr i'm probably missing it, but i can't seem to be able to create tickets on jira...

**Pull request merged**
