### PR TITLE
Update research plan

### PR DESCRIPTION
**Pull request by ssatagopan**
# [Update Research Plan](https://github.com/OHS-Hosting-Infrastructure/infrastructure/issues/47)

### CODE REVIEW

**Review by kilbergr — COMMENTED** [review]
From what Matt was talking about, I was thinking we might want to organize the questions with the workshops where they were addressed and add more visual aids. Do you mind if I work directly on this branch with you?

**Comment by ssatagopan** [comment]
> From what Matt was talking about, I was thinking we might want to organize the questions with the workshops where they were addressed and add more visual aids. Do you mind if I work directly on this branch with you?

No problem, that's why I didn't initial branch name

**Comment by kilbergr** [comment]
@ssatagopan looking for your reaction. Sorry it took so long to get to.

**Comment by ssatagopan** [comment]
> @ssatagopan looking for your reaction. Sorry it took so long to get to.

I think content is good, but would recommend numbering the different activities in both the descriptive area and the timeline so that it's easier to match up.

**Review by jduss4 — APPROVED** [review]

**Comment by kilbergr** [comment]
Have a 👍 from Matt on Slack: https://trussworks.slack.com/archives/C01T6F5PB1A/p1623955227036900?thread_ts=1623779688.015000&cid=C01T6F5PB1A

**Pull request merged**
