### PR TITLE
Remove shared slack channel intro onboarding step

### PR DESCRIPTION
**Pull request by rpdelaney**
# Not Jira

- Remove shared slack channel intro onboarding step

Per Sanjay, we are no longer using this channel in favor of the shared OHS workspace.

### CODE REVIEW

**Review by ssatagopan — CHANGES_REQUESTED** [review]
Instead of removing step, can you update with link and mention of #general channel in OHS workspace?

**Comment by rpdelaney** [comment]
@ssatagopan Can do. Should we also ask folks to introduce themselves in the shared OHS slack like we did before?

**Comment by ssatagopan** [comment]
> @ssatagopan Can do. Should we also ask folks to introduce themselves in the shared OHS slack like we did before?

Yes please

**Comment by rpdelaney** [comment]
47d7651

**Review by ssatagopan — APPROVED** [review]

**Pull request merged**
