### PR TITLE
Rek 151 alert dd

### PR DESCRIPTION
**Pull request by kilbergr**
# [System monitoring and notifications ](https://github.com/OHS-Hosting-Infrastructure/infrastructure/issues/151)

Changes proposed in this pull request:

- Add a mini design doc describing how we're thinking to manage our simple alerting system.

As you could probably guess by how long it took me to make something so small, I am not totally sure what questions should be answered here. Any suggestions are welcomed.

### CODE REVIEW

**Comment by ssatagopan** [comment]
Overall, it looks fine to me, but it seems like we're recommending using PagerDuty instead of doing the alerts in AWS SNS. Do you want to include the configuration of PagerDuty in this doc?

Separately, this applies more to the monitoring dd, would the monitors that you describe in the dd have caught the issues in the last few outages?

**Review by ssatagopan — COMMENTED** [review]
Overall, it looks fine to me, but it seems like we're recommending using PagerDuty instead of doing the alerts in AWS SNS. Do you want to include the configuration of PagerDuty in this doc?

Separately, this applies more to the monitoring dd, would the monitors that you describe in the dd have caught the issues in the last few outages?

**Comment by kilbergr** [comment]
The 5xx Status Codes should have caught those issues.

**Review by ssatagopan — APPROVED** [review]
LGTM

**Pull request merged**
